### ISSUE TITLE
Añadir/mejorar la documentación de los datos

### ISSUE THREAD

**Issue by matcasti** [matcasti/mammals#2]
- Hay que añadir documentación de las variables usadas, si es que se mantendrán con el mismo nombre (o no). 
- Hay que añadir información adicional que sea relevante al paquete, fuentes, referencias, etc. Todo lo que sirva para darle contexto al usuario del paquete que use los datos

**Comment by matcasti** [comment]
@littlecharlotte te podrás encargar de esto?

**Comment by littlecharlotte** [comment]
Si yo me encargo

>

**Comment by littlecharlotte** [comment]
Las variables usadas son: 
- una medida de abundancia poblacional, esto puede ser cantidad de individuos o cualquier proxy que de cuenta del tamaño poblacional
- una medida temporal, es decir el intervalo de tiempo en que se está contabilizando la abundncia poblacional, esto puede ser a escala mensual, anual, decadal, entre otros
Esas son las dos variables que se requieren para poder realizar los modelos de dinamica poblacional.
Ahora, si los estudios tienen más información como por ejemplo el muestreo en varios sitios, entonces tiene que haber una variable que sea sitio, es decir el nombre del lugar al que pertenece dicha población.
En nuestro caso hay otras variables categoricas que informan sobre diversas caracteristicas de los datos como, que tan completo está el censo o que tan relevante es el sitio para su analisis. Tambien si la colonia es reproductiva. Por ultimo, la variable tamaño poblacional que utilicé es la que contempla a todos los individuos de la poblacion sin discriminar entre genero o edad. Sin embargo, se pueden hacer variables específicas y denominarlas hembras, machos, juveniles, cachorros y de esa manera se puede calcular la tasa de cambio pero para cada una de las categorias por separado

**Comment by matcasti** [comment]
Gracias @littlecharlotte!

La base de datos de la isla juan fernandez se cambió a su propio paquete: [`jffs`](https://github.com/mammal-proj/jffs). Este estará orientado a exploración de esos datos, mientras que este paquete lo dedicaremos exclusivamente al desarrollo a largo plazo de funciones y herramientas para en análisis de dinámica de poblaciones.
